title: title of this website
languageCode: en-us
titleCaseStyle: none
capitalizeListTitles: false
pluralizeListTitles: false
enableGitInfo: true
pygmentsUseClasses: true
disableHugoGeneratorInject: true

relativeURLs: false
# canonifyURLs: true

baseURL: https://booklice.github.io/hugo_with_cms/

date:
  locale: ko_KR

uglyURLs: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    lineNumbersInTable: false
    tabWidth: 4

menu:
  main:
    - identifier: about
      name: about
      url: /about.html
      weight: 1

    - identifier: posts
      name: posts
      url: /posts.html
      weight: 2
